import { StyleSheet } from 'react-native';

export const ui = {
    iconSizeSm: 16,
    iconSizeMd: 18,
    accent: '#D1495B',
    warm: '#B85C38',
    deep: '#A3324A',
    muted: '#A36A62',
    light: '#FFF4EF',
    growth: '#B33C55',
};

export const styles = StyleSheet.create({
    screen: {
        flex: 1,
        backgroundColor: '#FFF3F0',
    },
    contentContainer: {
        paddingHorizontal: 20,
        paddingTop: 28,
        paddingBottom: 40,
    },
    container: {
        alignItems: 'center',
        gap: 18,
    },
    heroCard: {
        width: '100%',
        backgroundColor: '#FFF9F7',
        borderRadius: 28,
        paddingHorizontal: 22,
        paddingVertical: 26,
        borderWidth: 1,
        borderColor: '#F4C8C0',
        shadowColor: '#D68A8E',
        shadowOpacity: 0.18,
        shadowOffset: {
            width: 0,
            height: 14,
        },
        shadowRadius: 24,
        elevation: 6,
        alignItems: 'center',
    },
    heroBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        backgroundColor: '#FFE7E1',
        borderRadius: 999,
        paddingHorizontal: 14,
        paddingVertical: 8,
        marginBottom: 16,
    },
    heroBadgeText: {
        color: '#B8445A',
        fontSize: 13,
        fontWeight: '700',
        letterSpacing: 0.4,
    },
    title: {
        fontSize: 38,
        fontWeight: '900',
        color: '#D1495B',
        textAlign: 'center',
        marginBottom: 12,
    },
    subtitle: {
        fontSize: 18,
        color: '#5B3A29',
        textAlign: 'center',
        lineHeight: 28,
        maxWidth: 620,
    },
    heroIconRow: {
        flexDirection: 'row',
        gap: 12,
        marginTop: 20,
    },
    heroIconBubble: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: '#FFE5E8',
        alignItems: 'center',
        justifyContent: 'center',
    },
    heroIconBubbleWarm: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: '#FFE8D8',
        alignItems: 'center',
        justifyContent: 'center',
    },
    heroIconBubbleSoft: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: '#FDE7F1',
        alignItems: 'center',
        justifyContent: 'center',
    },
    sectionCard: {
        width: '100%',
        backgroundColor: '#FFF8F4',
        borderRadius: 28,
        padding: 22,
        borderWidth: 1,
        borderColor: '#F0D5CA',
    },
    sectionCardAccent: {
        width: '100%',
        backgroundColor: '#FFF1EC',
        borderRadius: 28,
        padding: 22,
        borderWidth: 1,
        borderColor: '#F3C2BA',
    },
    sectionCardDark: {
        width: '100%',
        backgroundColor: '#A23E4D',
        borderRadius: 30,
        padding: 22,
        borderWidth: 1,
        borderColor: '#B85B69',
        shadowColor: '#7E2D3B',
        shadowOpacity: 0.24,
        shadowOffset: {
            width: 0,
            height: 14,
        },
        shadowRadius: 24,
        elevation: 8,
    },
    sectionCardCollapsed: {
        paddingVertical: 16,
        paddingHorizontal: 18,
        borderRadius: 22,
    },
    sectionCardDarkCollapsed: {
        paddingVertical: 16,
        paddingHorizontal: 18,
        borderRadius: 22,
    },
    sectionToggle: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 12,
    },
    sectionTitle: {
        color: '#A3324A',
        fontSize: 19,
        fontWeight: '800',
        flexShrink: 1,
        textAlign: 'center',
    },
    sectionTitleLight: {
        color: '#FFF4EF',
        fontSize: 19,
        fontWeight: '800',
        flexShrink: 1,
        textAlign: 'center',
    },
    sectionSubtitle: {
        color: '#7A5751',
        fontSize: 15,
        lineHeight: 24,
        marginTop: 12,
        marginBottom: 18,
    },
    sectionSubtitleLight: {
        color: '#F8D9D1',
        fontSize: 15,
        lineHeight: 24,
        marginTop: 12,
        marginBottom: 18,
    },
    reasonList: {
        gap: 12,
    },
    reasonCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 22,
        padding: 16,
        borderWidth: 1,
        borderColor: '#F3D6CF',
    },
    reasonCardOpen: {
        borderColor: '#E6A9B1',
        backgroundColor: '#FFF7F8',
    },
    reasonHeader: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    reasonIconWrap: {
        width: 42,
        height: 42,
        borderRadius: 21,
        backgroundColor: '#FFE6EA',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
    },
    reasonTextWrap: {
        flex: 1,
        paddingRight: 8,
    },
    reasonMonth: {
        color: '#B85B6B',
        fontSize: 12,
        fontWeight: '800',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
        marginBottom: 4,
    },
    reasonTitle: {
        color: '#5C3930',
        fontSize: 16,
        fontWeight: '700',
        lineHeight: 22,
    },
    reasonDescription: {
        color: '#7A5751',
        fontSize: 14,
        lineHeight: 23,
        marginTop: 14,
        paddingTop: 14,
        borderTopWidth: 1,
        borderTopColor: '#F3D9D2',
    },
    growthList: {
        gap: 14,
    },
    growthCard: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        backgroundColor: '#FFF9F7',
        borderRadius: 22,
        padding: 16,
        borderWidth: 1,
        borderColor: '#F2D3CC',
    },
    growthIconWrap: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: '#FFE7E1',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 14,
    },
    growthTextWrap: {
        flex: 1,
    },
    growthTitle: {
        color: '#A53D52',
        fontSize: 17,
        fontWeight: '800',
        marginBottom: 6,
    },
    growthText: {
        color: '#6E4E47',
        fontSize: 14,
        lineHeight: 23,
    },
    beforeAfterGrid: {
        gap: 14,
    },
    beforeAfterCard: {
        backgroundColor: 'rgba(255, 247, 244, 0.08)',
        borderRadius: 24,
        padding: 18,
        borderWidth: 1,
        borderColor: 'rgba(255, 232, 224, 0.18)',
    },
    beforeAfterIconWrap: {
        width: 42,
        height: 42,
        borderRadius: 21,
        backgroundColor: 'rgba(255, 244, 239, 0.16)',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 12,
    },
    beforeAfterTitle: {
        color: '#FFF7F4',
        fontSize: 18,
        fontWeight: '800',
        marginBottom: 14,
    },
    beforeAfterBlockMuted: {
        backgroundColor: 'rgba(255, 233, 224, 0.1)',
        borderRadius: 18,
        padding: 14,
        marginBottom: 12,
    },
    beforeAfterBlockBright: {
        backgroundColor: '#FFF2EE',
        borderRadius: 18,
        padding: 14,
    },
    beforeAfterLabelMuted: {
        color: '#FFDCD4',
        fontSize: 12,
        fontWeight: '800',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
        marginBottom: 8,
    },
    beforeAfterTextMuted: {
        color: '#FFF1EC',
        fontSize: 14,
        lineHeight: 23,
    },
    beforeAfterLabelBright: {
        color: '#B03E52',
        fontSize: 12,
        fontWeight: '800',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
        marginBottom: 8,
    },
    beforeAfterTextBright: {
        color: '#6A4640',
        fontSize: 14,
        lineHeight: 23,
    },
});
