import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    legendCard: {
        width: '100%',
        backgroundColor: '#FFE4DA',
        borderRadius: 22,
        borderWidth: 1,
        borderColor: '#F2C5B7',
        paddingVertical: 14,
        paddingHorizontal: 16,
        marginBottom: 18,
    },
    legendTitle: {
        fontSize: 15,
        fontWeight: '800',
        color: '#A3324A',
        textAlign: 'center',
        marginBottom: 6,
    },
    legendText: {
        fontSize: 14,
        color: '#6D4D47',
        textAlign: 'center',
        lineHeight: 22,
    },
    mapCard: {
        position: 'relative',
        overflow: 'hidden',
        borderRadius: 30,
        backgroundColor: '#F8E4C7',
        borderWidth: 1,
        borderColor: '#D8BB93',
        shadowColor: '#B58263',
        shadowOpacity: 0.18,
        shadowOffset: {
            width: 0,
            height: 10,
        },
        shadowRadius: 18,
        elevation: 5,
    },
    mapTexture: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: '#F6E1BE',
        opacity: 0.55,
    },
    pathCanvas: {
        ...StyleSheet.absoluteFillObject,
    },
    mapNodeWrap: {
        position: 'absolute',
        alignItems: 'center',
    },
    mapNodeButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#D1495B',
        padding: 4,
        borderWidth: 2,
        borderColor: '#FFF4EA',
        shadowColor: '#9B4250',
        shadowOpacity: 0.24,
        shadowOffset: {
            width: 0,
            height: 6,
        },
        shadowRadius: 10,
        elevation: 4,
    },
    mapNodeButtonPressed: {
        transform: [{ scale: 0.96 }],
        opacity: 0.92,
    },
    mapNodeInner: {
        flex: 1,
        borderRadius: 999,
        backgroundColor: '#FCEDE8',
        alignItems: 'center',
        justifyContent: 'center',
    },
    mapNodeIndex: {
        color: '#B3384C',
        fontSize: 15,
        fontWeight: '800',
    },
    mapLabelPill: {
        marginTop: 8,
        backgroundColor: 'rgba(255, 248, 241, 0.92)',
        borderRadius: 999,
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderWidth: 1,
        borderColor: '#E2C8A6',
    },
    mapLabelText: {
        color: '#7A5643',
        fontSize: 11,
        fontWeight: '700',
    },
    finishBadge: {
        position: 'absolute',
        right: 18,
        bottom: 18,
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: '#A3324A',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 2,
        borderColor: '#F9E9DB',
    },
    finishBadgeText: {
        color: '#FFF4EA',
        fontSize: 18,
        fontWeight: '900',
    },
    footerHint: {
        marginTop: 16,
        fontSize: 13,
        color: '#7A5751',
        textAlign: 'center',
        lineHeight: 21,
        maxWidth: 340,
    },
});