import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FFF3F0',
    },
    contentContainer: {
        paddingHorizontal: 24,
        paddingTop: 24,
        paddingBottom: 30,
    },
    card: {
        backgroundColor: '#FFE1DA',
        borderRadius: 22,
        borderWidth: 1,
        borderColor: '#F2BFB2',
        paddingVertical: 18,
        paddingHorizontal: 16,
        shadowColor: '#B15F6D',
        shadowOpacity: 0.16,
        shadowOffset: {
            width: 0,
            height: 8,
        },
        shadowRadius: 12,
        elevation: 4,
    },
    title: {
        fontSize: 24,
        fontWeight: '800',
        color: '#D1495B',
        textAlign: 'center',
        marginBottom: 10,
    },
    subtitle: {
        fontSize: 16,
        color: '#5B3A29',
        textAlign: 'center',
        marginBottom: 18,
        lineHeight: 22,
    },
    row: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 18,
    },
    input: {
        width: 88,
        height: 52,
        backgroundColor: '#FFF7F4',
        borderRadius: 14,
        borderWidth: 1,
        borderColor: '#F0C8BD',
        textAlign: 'center',
        fontSize: 24,
        fontWeight: '700',
        color: '#A53A6D',
    },
    separator: {
        fontSize: 28,
        color: '#A53A6D',
        marginHorizontal: 10,
        marginBottom: 2,
        fontWeight: '700',
    },
    helperText: {
        fontSize: 14,
        color: '#7A5751',
        textAlign: 'center',
        marginBottom: 16,
    },
    daysTitle: {
        fontSize: 15,
        fontWeight: '700',
        color: '#8E4A57',
        textAlign: 'center',
        marginBottom: 4,
    },
    daysSubtitle: {
        fontSize: 13,
        color: '#7A5751',
        textAlign: 'center',
        marginBottom: 10,
    },
    daysGrid: {
        gap: 8,
        marginBottom: 16,
    },
    dayItem: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#F0C8BD',
        borderRadius: 12,
        backgroundColor: '#FFF7F4',
        paddingVertical: 10,
        paddingHorizontal: 12,
    },
    dayItemSelected: {
        borderColor: '#D1495B',
        backgroundColor: '#FFEDE8',
    },
    checkbox: {
        width: 22,
        height: 22,
        borderRadius: 6,
        borderWidth: 1,
        borderColor: '#CFA2AD',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 10,
        backgroundColor: '#FFFFFF',
    },
    checkboxSelected: {
        backgroundColor: '#D1495B',
        borderColor: '#D1495B',
    },
    checkboxCheck: {
        color: '#FFF7F4',
        fontSize: 13,
        fontWeight: '800',
    },
    dayLabel: {
        color: '#5B3A29',
        fontSize: 15,
        fontWeight: '600',
    },
    dayLabelSelected: {
        color: '#A53A6D',
    },
    saveButton: {
        backgroundColor: '#D1495B',
        borderRadius: 14,
        height: 48,
        alignItems: 'center',
        justifyContent: 'center',
    },
    saveButtonText: {
        color: '#FFF7F4',
        fontSize: 16,
        fontWeight: '700',
    },
    feedback: {
        marginTop: 14,
        textAlign: 'center',
        color: '#8E4A57',
        fontWeight: '600',
    },
});
