import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FFF3F0',
    },
    contentContainer: {
        justifyContent: 'flex-start',
        alignItems: 'center',
        paddingHorizontal: 24,
        paddingTop: 56,
        paddingBottom: 28,
    },
    counterCard: {
        width: '100%',
        position: 'relative',
        top: -40,
        backgroundColor: '#FFE1DA',
        borderRadius: 22,
        borderWidth: 1,
        borderColor: '#F2BFB2',
        paddingVertical: 18,
        paddingHorizontal: 16,
        marginBottom: 28,
        shadowColor: '#B15F6D',
        shadowOpacity: 0.16,
        shadowOffset: {
            width: 0,
            height: 8,
        },
        shadowRadius: 12,
        elevation: 4,
    },
    counterTitle: {
        fontSize: 14,
        fontWeight: '700',
        color: '#8E4A57',
        textTransform: 'uppercase',
        letterSpacing: 0.8,
        textAlign: 'center',
        marginBottom: 10,
    },
    counterPrimaryValue: {
        fontSize: 24,
        fontWeight: '800',
        color: '#B23A48',
        textAlign: 'center',
        marginBottom: 8,
    },
    counterSecondaryValue: {
        fontSize: 14,
        color: '#5B3A29',
        textAlign: 'center',
        lineHeight: 20,
        marginBottom: 6,
    },
    counterStartDate: {
        fontSize: 13,
        color: '#7A5751',
        textAlign: 'center',
    },
    title: {
        fontSize: 30,
        fontWeight: '800',
        textAlign: 'center',
        color: '#D1495B',
        marginBottom: 12,
    },
    subtitle: {
        fontSize: 18,
        textAlign: 'center',
        color: '#5B3A29',
        lineHeight: 26,
    },
    appPurposeCard: {
        width: '100%',
        marginTop: 16,
        backgroundColor: '#FFE1DA',
        borderRadius: 18,
        borderWidth: 1,
        borderColor: '#F2BFB2',
        paddingVertical: 14,
        paddingHorizontal: 14,
    },
    appPurposeTitle: {
        fontSize: 14,
        fontWeight: '700',
        color: '#8E4A57',
        textTransform: 'uppercase',
        letterSpacing: 0.7,
        marginBottom: 8,
        textAlign: 'center',
    },
    appPurposeText: {
        fontSize: 15,
        color: '#5B3A29',
        textAlign: 'center',
        lineHeight: 23,
    },
    nextCouponCard: {
        width: '100%',
        marginTop: 20,
        backgroundColor: '#FFE1DA',
        borderRadius: 18,
        borderWidth: 1,
        borderColor: '#F2BFB2',
        paddingVertical: 14,
        paddingHorizontal: 14,
    },
    nextCouponLabel: {
        fontSize: 13,
        fontWeight: '700',
        color: '#8E4A57',
        textTransform: 'uppercase',
        letterSpacing: 0.7,
        marginBottom: 8,
        textAlign: 'center',
    },
    nextCouponTitle: {
        fontSize: 19,
        fontWeight: '800',
        color: '#B23A48',
        textAlign: 'center',
        marginBottom: 6,
    },
    nextCouponCountdown: {
        fontSize: 14,
        color: '#5B3A29',
        textAlign: 'center',
        lineHeight: 20,
    },
    nextCouponReady: {
        fontSize: 15,
        color: '#5B3A29',
        textAlign: 'center',
        lineHeight: 22,
        fontWeight: '600',
    },
});
